FROM node:20-alpine AS base

WORKDIR /usr/src/app
ENV NODE_ENV=development

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps/backend/package.json apps/backend/package.json
COPY apps/frontend/package.json apps/frontend/package.json

RUN yarn install --immutable

COPY . .

EXPOSE 4000 5173

CMD ["yarn", "workspace", "@node-crm/backend", "dev"]
